---
downloads: ~/.ansible-downloads/

configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/yn/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/code/mine/dotfiles
dotfiles_files:
  - .gitconfig
  - .gitignore_global
  - .ssh/config

homebrew_installed_packages: []
  # # - ansible # Installed via Pip.
  # - autoconf
  # - bash-completion
  # - chromedriver
  # - doxygen
  # - gettext
  # - gifsicle
  # - git
  # - go
  # - gpg
  # - hub
  # - httpie
  # - iperf
  # - libevent
  # - sqlite
  # - mcrypt
  # - nmap
  # - npm
  # - nvm
  # - ssh-copy-id
  # - cowsay
  # - readline
  # - openssl
  # - pv
  # - wget
  # - wrk

homebrew_taps: []
  # - homebrew/core
  # - caskroom/cask
  # - homebrew/binary
  # - homebrew/dupes
  # - homebrew/php
  # - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps: []
  # - docker
  # - dropbox
  # # - fing # Download link keeps getting changed, d'oh!
  # - firefox
  # - google-chrome
  # - handbrake
  # - licecap
  # - limechat
  # - macvim
  # - nvalt
  # - sequel-pro
  # - skitch
  # - slack
  # - sublime-text
  # - transmit
  # - vagrant
  # - virtualbox

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 413857545, name: "Divvy - Window Manager"}
mas_email: "yuri.niyazov@gmail.com"
mas_password: ""
